version: YW.{build}
image: Visual Studio 2017 Preview
clone_folder: C:\Projects\WitSharp
skip_commits:
  message: /Update/
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
after_build:
- cmd: dotnet build
artifacts:
- path: '**\*.nupkg'
  name: WitSharp
deploy:
- provider: NuGet
  server: https://www.nuget.org/api/v2/package
  api_key:
    secure: iZ4sXMiLBYQi2UHPlGgqPvQKMgB8oYlfsOuckZzQ4Zm9GEcdpkRVLNabwfHt0AL9
  artifact: WitSharp
