namespace Wit.Net.Objects
{
    using System;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    public partial class SentenceObject
    {
        /// <summary>Either the ID you passed to the API or an ID generated by the API</summary>
        [JsonProperty("msg_id")]
        public string MessageId { get; internal set; }
        /// <summary>Either the text sent in the q argument or the transcript of the speech input. This value should be used only for debug as Wit.ai focuses on entities.</summary>
        [JsonProperty("_text")]
        public string Text { get; internal set; }
        /// <summary>Object of entities. Each entity will contain an array [] of values even if there is only one value.</summary>
        [JsonProperty("entities")]
        public Entities Entities { get; internal set; }
    }

    /// <summary> Provides a list of all intents</summary>
    public partial class Entities
    {
        [JsonProperty("intent")]
        public List<Intent> Intent { get; internal set; }
        [JsonProperty("metric")]
        public List<Metric> Metric { get; internal set; }
        [JsonProperty("datetime")]
        public List<Datetime> Datetime { get; internal set; }
    }


    public partial class Intent
    {
        [JsonProperty("Unit")]
        public string Unit { get; internal set; }
        [JsonProperty("value")]
        public string Value { get; internal set; }
        [JsonProperty("confidence")]
        public double Confidence { get; internal set; }
    }

    public partial class Datetime
    {
        [JsonProperty("value")]
        public Value Value { get; internal set; }
        [JsonProperty("confidence")]
        public long? Confidence { get; internal set; }
    }

    public partial class Value
    {
        [JsonProperty("to")]
        public DateTimeOffset? To { get; internal set; }
        [JsonProperty("from")]
        public DateTimeOffset? From { get; internal set; }
    }

    public partial class Metric
    {
        [JsonProperty("value")]
        public string Value { get; internal set; }
        [JsonProperty("metadata")]
        public string Metadata { get; internal set; }
        [JsonProperty("confidence")]
        public double? Confidence { get; internal set; }
    }

    public partial class Stats
    {

        [JsonProperty("total_time")]
        public int TotalTime { get; internal set; }
    }
}
