namespace WitSharp.Models
{
    using WitSharp.Objects;
    public class SentenceModel
    {
        /// <summary>User’s query. Length must be  between 0 and 256</summary>
        public string Message { get; set; }
        /// <summary>If no context is provided, default will be used.</summary>
        public ContextObject Context { get; set; }
        /// <summary>by default a LONG id will be generated by WitSharp if none is provided.</summary>
        public string MessageId { get; set; }
        /// <summary>by default a LONG id will be generated by WitSharp if none is provided.</summary>
        public string ThreadId { get; set; }
        /// <summary>The number of n-best trait entities you want to get back. The Default is 1, and the maximum is 8.</summary>
        public int MaxTraits { get; set; } = 1;
        /// <summary>A flag to get auxiliary information about entities, like the location within the sentence.</summary>
        public bool Verbose { get; set; } = false;
    }
}